version: '3.10'


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bike_rental
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=bike_rental
      - POSTGRES_USER=gigerin
      - POSTGRES_PASSWORD=80808080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - bike_rental_network

  celery:
    build: .
    command: celery -A bike_rental worker --loglevel=info
    volumes:
      - .:/bike_rental
    environment:
      - DJANGO_DB_NAME=bike_rental
      - DJANGO_DB_USER=gigerin
      - DJANGO_DB_PASSWORD=80808080
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - bike_rental_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bike_rental
      POSTGRES_USER: gigerin
      POSTGRES_PASSWORD: 80808080
    ports:
      - "5432:5432"
    networks:
      - bike_rental_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - bike_rental_network

networks:
  bike_rental_network:
    driver: bridge


